// @domain investments
// @tables investment_projects,investment_project_compliance,investment_share_links,investment_share_views,investors,investor_interests,investment_packages,standard_kpi_mappings,standards_audit_snapshots,collection_protocols
// @ui src/routes/_authenticated/admin/countries.$code.investments.tsx
//
// Row shapes for the tables and columns added by drizzle/migrations/0009.
//
// src/integrations/supabase/types.ts is generated by Lovable and must not be
// edited by hand. Until Lovable regenerates it after applying 0009, queries on
// the new tables go through `db()`, which drops the generated table typing,
// and results are cast to the interfaces below. Once types.ts knows these
// tables, `db()` can be replaced by the typed client and this file reduced to
// re-exports.

import type { SupabaseClient } from "@supabase/supabase-js";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AnyClient = SupabaseClient<any, any, any>;

/** The same client without generated table types. See the note above. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function db(sb: AnyClient): SupabaseClient<any> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return sb as unknown as SupabaseClient<any>;
}

export type ApprovalStatus = "draft" | "submitted" | "approved" | "returned" | "withdrawn";
export type PlanStatus = "draft" | "submitted" | "approved" | "returned";

export interface CollectionPlanRow {
  id: string;
  country_code: string;
  requirement_id: string;
  owner_agency: string | null;
  method: string;
  cadence: string;
  validation_rules: string | null;
  due_date: string | null;
  notes: string | null;
  status: PlanStatus;
  version: number;
  created_by: string | null;
  submitted_by: string | null;
  submitted_at: string | null;
  approved_by: string | null;
  approved_at: string | null;
  returned_by: string | null;
  returned_at: string | null;
  returned_note: string | null;
  created_at: string;
  updated_at: string;
}

export interface InvestmentProjectRow {
  id: string;
  country_code: string;
  title: string;
  sector: string | null;
  structure: string | null;
  stage: string;
  capex_usd: number | null;
  revenue_model: string | null;
  sponsor: string | null;
  es_category: string | null;
  summary: string | null;
  risks: string | null;
  climate_alignment: string | null;
  aml_cleared: boolean;
  bo_disclosed: boolean;
  feasibility_done: boolean;
  land_secured: boolean;
  approval_status: ApprovalStatus;
  version: number;
  created_by: string | null;
  submitted_by: string | null;
  submitted_at: string | null;
  approved_by: string | null;
  approved_at: string | null;
  returned_by: string | null;
  returned_at: string | null;
  returned_note: string | null;
  created_at: string;
  updated_at: string;
}

/** Columns safe to show anyone with country access, and — once approved — investors. */
export const PUBLIC_PROJECT_COLUMNS =
  "id,country_code,title,sector,structure,stage,capex_usd,summary,revenue_model,sponsor,es_category,climate_alignment,risks,version,approval_status,approved_at,updated_at";

export interface BeneficialOwner {
  name: string;
  nationality?: string | null;
  ownership_pct?: number | null;
  is_pep?: boolean | null;
  evidence?: string | null;
  legacy?: boolean;
}

export interface ComplianceRow {
  project_id: string;
  country_code: string;
  beneficial_owners: BeneficialOwner[];
  aml_status: "not_started" | "in_progress" | "cleared" | "failed";
  aml_reference: string | null;
  aml_cleared_by: string | null;
  aml_cleared_at: string | null;
  notes: string | null;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface ShareLinkRow {
  id: string;
  project_id: string;
  country_code: string;
  token_hash: string;
  token_hint: string;
  label: string;
  allow_interest: boolean;
  include_packages: PackageKind[];
  max_views: number | null;
  view_count: number;
  last_viewed_at: string | null;
  expires_at: string;
  revoked_at: string | null;
  revoked_by: string | null;
  created_by: string | null;
  created_at: string;
}

export interface ShareViewRow {
  id: string;
  link_id: string;
  country_code: string;
  viewed_at: string;
  visitor_hash: string | null;
  user_agent: string | null;
  referrer: string | null;
  event: "view" | "package_open" | "interest";
}

export const INVESTOR_KINDS = [
  "dfi",
  "mdb",
  "sovereign_fund",
  "pension",
  "infrastructure_fund",
  "private_equity",
  "strategic",
  "family_office",
  "bank",
  "other",
] as const;
export type InvestorKind = (typeof INVESTOR_KINDS)[number];
export const INVESTOR_KIND_LABEL: Record<InvestorKind, string> = {
  dfi: "Development finance institution",
  mdb: "Multilateral development bank",
  sovereign_fund: "Sovereign wealth fund",
  pension: "Pension fund",
  infrastructure_fund: "Infrastructure fund",
  private_equity: "Private equity",
  strategic: "Strategic / operator",
  family_office: "Family office",
  bank: "Commercial bank",
  other: "Other",
};

export type KycStatus = "not_started" | "in_progress" | "cleared" | "failed";

export interface InvestorRow {
  id: string;
  country_code: string;
  name: string;
  kind: InvestorKind;
  hq_country: string | null;
  website: string | null;
  contact_name: string | null;
  contact_email: string | null;
  ticket_min_usd: number | null;
  ticket_max_usd: number | null;
  sectors: string[];
  kyc_status: KycStatus;
  notes: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export const INTEREST_STAGES = [
  "identified",
  "contacted",
  "nda_signed",
  "data_room",
  "due_diligence",
  "indicative_offer",
  "term_sheet",
  "closed_won",
  "closed_lost",
] as const;
export type InterestStage = (typeof INTEREST_STAGES)[number];
export const INTEREST_STAGE_LABEL: Record<InterestStage, string> = {
  identified: "Identified",
  contacted: "Contacted",
  nda_signed: "NDA signed",
  data_room: "Data room",
  due_diligence: "Due diligence",
  indicative_offer: "Indicative offer",
  term_sheet: "Term sheet",
  closed_won: "Closed — won",
  closed_lost: "Closed — lost",
};
/** Gates enforced by public.investor_interests_guard(); shown in the UI before the user hits them. */
export const INTEREST_STAGE_GATE: Partial<Record<InterestStage, string>> = {
  nda_signed: "Needs the NDA signature date.",
  data_room: "Needs the NDA signature date.",
  due_diligence: "Needs a matched investor with KYC cleared.",
  indicative_offer: "Needs a matched investor with KYC cleared.",
  term_sheet: "Needs a matched investor with KYC cleared.",
  closed_won: "Needs a matched investor with KYC cleared.",
  closed_lost: "Needs a reason.",
};

export interface InterestRow {
  id: string;
  country_code: string;
  project_id: string;
  investor_id: string | null;
  share_link_id: string | null;
  source: "manual" | "share_link";
  stage: InterestStage;
  indicative_amount_usd: number | null;
  next_step: string | null;
  next_step_due: string | null;
  owner_id: string | null;
  contact_name: string | null;
  contact_email: string | null;
  organisation: string | null;
  message: string | null;
  nda_signed_at: string | null;
  lost_reason: string | null;
  created_at: string;
  updated_at: string;
}

export const PACKAGE_KINDS = ["teaser", "memorandum", "data_room", "deck"] as const;
export type PackageKind = (typeof PACKAGE_KINDS)[number];
export const PACKAGE_KIND_LABEL: Record<PackageKind, string> = {
  teaser: "Teaser",
  memorandum: "Information memorandum",
  data_room: "Data-room index",
  deck: "Investor deck",
};

export interface PackageRow {
  id: string;
  project_id: string;
  country_code: string;
  kind: PackageKind;
  version: number;
  project_version: number;
  status: "draft" | "approved" | "superseded";
  content: unknown;
  facts: unknown;
  model: string | null;
  created_by: string | null;
  created_at: string;
  approved_by: string | null;
  approved_at: string | null;
}

export interface MappingRow {
  id: string;
  country_code: string;
  requirement_id: string;
  kpi_code: string;
  status: "suggested" | "accepted" | "rejected";
  confidence: number | null;
  rationale: string | null;
  suggested_by: string | null;
  decided_by: string | null;
  decided_at: string | null;
  created_at: string;
}

export interface AuditSnapshotRow {
  id: string;
  country_code: string;
  period_label: string;
  computed_at: string;
  coverage_pct: number;
  weighted_pct: number;
  counts: Record<string, number>;
  by_standard: Array<{ code: string; met: number; total: number; weightedPct?: number }>;
  rows: Array<{ id: string; status: string }>;
}

export interface HistoryEntry {
  id: string;
  action: string;
  actor_id: string | null;
  actor_label: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

/** governance_history() — the country-scoped read of audit_log. */
export async function loadHistory(
  sb: AnyClient,
  targetType: string,
  targetId: string,
): Promise<HistoryEntry[]> {
  const { data, error } = await db(sb).rpc("governance_history", {
    _target_type: targetType,
    _target_id: targetId,
  });
  if (error) throw new Error(error.message);
  return (data ?? []) as HistoryEntry[];
}

/** Capabilities the caller holds for a country, for showing the right actions. */
export async function loadCapabilities(
  sb: AnyClient,
  userId: string,
  code: string,
): Promise<{ approvePlans: boolean; approveInvestments: boolean; compliance: boolean }> {
  const c = db(sb);
  const [a, b, d] = await Promise.all([
    c.rpc("can_approve_protocol", { _user_id: userId, _country_code: code }),
    c.rpc("can_approve_investment", { _user_id: userId, _country_code: code }),
    c.rpc("can_manage_compliance", { _user_id: userId, _country_code: code }),
  ]);
  return { approvePlans: !!a.data, approveInvestments: !!b.data, compliance: !!d.data };
}

/** Turns a Postgres trigger message into something a person can act on. */
export function governanceError(e: { message?: string } | null | undefined): Error {
  const msg = e?.message ?? "Something went wrong.";
  if (/row-level security/i.test(msg))
    return new Error("You don't have permission to do that for this country.");
  if (/duplicate key/i.test(msg)) return new Error("That already exists.");
  return new Error(msg.replace(/^ERROR:\s*/, ""));
}
