// Renders a Sector Development Plan to markdown. Pure. Used by the export
// action and the public API's plan resource.

import type { PlanRow, PlanSectionRow } from "./db";

export function planToMarkdown(
  plan: Pick<
    PlanRow,
    | "title"
    | "country_code"
    | "sector_code"
    | "version"
    | "status"
    | "approved_at"
    | "approval_mode"
    | "scope"
  >,
  countryName: string,
  sectorLabel: string,
  sections: Array<Pick<PlanSectionRow, "ordinal" | "heading" | "body_md" | "status" | "stage_key">>,
): string {
  const head = [
    `# Sector Development Plan · ${plan.title}`,
    "",
    `**Country:** ${countryName} (${plan.country_code})`,
    `**Sector:** ${sectorLabel}`,
    `**Version:** ${plan.version}`,
    `**Status:** ${plan.status}${plan.approved_at ? ` (approved ${plan.approved_at.slice(0, 10)}${plan.approval_mode === "sole_admin" ? ", sole approver, not counter-signed" : ""})` : ""}`,
    `**Lead ministry:** ${plan.scope.lead_ministry || "To be confirmed"}`,
    `**Horizon:** ${plan.scope.horizon_years} years`,
    "",
    "Generated by GDPVision · Sector Studio. Every section was written from the country's own corpus to the Sector Studio method; sections marked as gaps say what is missing.",
    "",
    "---",
    "",
  ];
  const body = [...sections]
    .sort((a, b) => a.ordinal - b.ordinal)
    .flatMap((s) => [
      `## ${s.ordinal} · ${s.heading}`,
      "",
      s.status === "gap" ? "> **Gap.** This section could not be grounded in the corpus." : null,
      s.status === "stale"
        ? "> **Out of date.** The corpus has changed since this section was written."
        : null,
      s.status === "pending" ? "_Not yet drafted._" : s.body_md.trim(),
      "",
    ])
    .filter((x): x is string => x != null);
  return [...head, ...body].join("\n");
}
