// Renders a PRD to markdown. Pure. Used by the export action and the public
// page's download; the same text is what a later phase commits to the repo.

import type { BrandTokens } from "./brand";
import type { PrdRow, SectionRow } from "./db";

export function prdToMarkdown(
  prd: Pick<PrdRow, "title" | "country_code" | "version" | "status" | "approved_at" | "scope">,
  countryName: string,
  sections: Array<Pick<SectionRow, "ordinal" | "heading" | "body_md" | "status" | "stage_key">>,
  brand: BrandTokens | null,
): string {
  const head = [
    `# PRD · ${prd.title}`,
    "",
    `**Country:** ${countryName} (${prd.country_code})`,
    `**Version:** ${prd.version}`,
    `**Status:** ${prd.status}${prd.approved_at ? ` (approved ${prd.approved_at.slice(0, 10)})` : ""}`,
    `**Platform:** ${prd.scope.platform_name || "To be confirmed"}`,
    `**Audiences:** ${prd.scope.audiences.join(", ") || "all"}`,
    "",
    "Generated by GDPVision · Digital Government Studio. Every section was written from the country's own corpus; sections marked as gaps say what is missing.",
    "",
    "---",
    "",
  ];
  const body = [...sections]
    .sort((a, b) => a.ordinal - b.ordinal)
    .flatMap((s) => [
      `## ${s.ordinal} · ${s.heading}`,
      "",
      s.status === "gap" ? "> **Gap.** This section could not be grounded in the corpus." : null,
      s.status === "stale"
        ? "> **Out of date.** The corpus has changed since this section was written."
        : null,
      s.status === "pending" ? "_Not yet drafted._" : s.body_md.trim(),
      "",
    ])
    .filter((x): x is string => x != null);
  const tokens = brand
    ? [
        "---",
        "",
        "## Appendix · Brand tokens",
        "",
        "| Token | Value |",
        "|---|---|",
        `| ink | ${brand.ink} |`,
        `| paper | ${brand.paper} |`,
        `| accent | ${brand.accent} |`,
        ...brand.borders.map((b, i) => `| border-${i + 1} | ${b} |`),
        "",
        ...brand.contrast.map(
          (c) =>
            `- ${c.role}: ${c.ratio}:1 (${c.aa_text ? "AA" : c.aa_large ? "AA large" : "fails"})`,
        ),
        "",
      ]
    : [];
  return [...head, ...body, ...tokens].join("\n");
}
