// Chamber 07 · Ministers track — the Quality Check. Client-safe and
// model-free.
//
// Two jobs. (1) No near-duplicates: fifty composites that are really five
// people repeated are worthless as a basis for synthesis. (2) Composites,
// never portraits: a persona must not be recognisable as a real office
// holder. The Prime Minister set uses stricter thresholds because the pool
// of Caribbean heads of government is small enough that a composite can
// resemble one by accident.

import type { PersonaRow } from "./db";

const STOP = new Set(
  "a an and are as at be by for from has have he her his in into is it its of on or she that the their they this to was were who with will would minister ministry government state".split(
    " ",
  ),
);

export function tokens(s: string): Set<string> {
  return new Set(
    s
      .toLowerCase()
      .replace(/[^a-z0-9 ]+/g, " ")
      .split(/\s+/)
      .filter((t) => t.length > 2 && !STOP.has(t)),
  );
}

export function jaccard(a: Set<string>, b: Set<string>): number {
  if (!a.size || !b.size) return 0;
  let inter = 0;
  for (const t of a) if (b.has(t)) inter++;
  return inter / (a.size + b.size - inter);
}

export function normalizedKey(p: Pick<PersonaRow, "career_route" | "archetype">): string {
  const k = (s: string) =>
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
  return `${k(p.career_route)}::${k(p.archetype)}`;
}

function fingerprint(p: Pick<PersonaRow, "archetype" | "summary" | "career_route">): Set<string> {
  return tokens(`${p.archetype} ${p.career_route} ${p.summary}`);
}

export interface RealHolder {
  name: string;
  bio: string;
  country: string;
}

export interface QaThresholds {
  duplicate: number;
  bio: number;
}

export function thresholdsFor(isHeadOfGovernment: boolean): QaThresholds {
  return isHeadOfGovernment ? { duplicate: 0.42, bio: 0.22 } : { duplicate: 0.5, bio: 0.3 };
}

export interface QaVerdict {
  slot: number;
  ok: boolean;
  similarity: number;
  nearest_slot: number | null;
  real_person_flag: boolean;
  notes: string[];
}

function nameParts(name: string): string[] {
  return name
    .toLowerCase()
    .replace(/[^a-z' -]+/g, " ")
    .split(/\s+/)
    .filter(
      (t) => t.length > 2 && !["hon", "the", "dr", "sir", "dame", "mr", "mrs", "ms"].includes(t),
    );
}

/**
 * Checks every persona against the earlier ones (by slot) and against the
 * real office holders. A failing slot is regenerated by the run.
 */
export function checkPersonas(
  personas: PersonaRow[],
  real: RealHolder[],
  t: QaThresholds,
  validSkillCodes: Set<string>,
): QaVerdict[] {
  const ordered = [...personas].sort((a, b) => a.slot_index - b.slot_index);
  const prints = ordered.map(fingerprint);
  const keys = ordered.map(normalizedKey);
  const realParts = real.map((r) => ({ ...r, parts: nameParts(r.name), bio: tokens(r.bio) }));

  return ordered.map((p, i) => {
    const notes: string[] = [];
    let similarity = 0;
    let nearest: number | null = null;
    for (let j = 0; j < i; j++) {
      const s = jaccard(prints[i]!, prints[j]!);
      if (s > similarity) {
        similarity = s;
        nearest = ordered[j]!.slot_index;
      }
      if (keys[i] === keys[j]) {
        similarity = Math.max(similarity, 1);
        nearest = ordered[j]!.slot_index;
      }
    }
    if (similarity >= t.duplicate)
      notes.push(`Too close to persona ${nearest} (${Math.round(similarity * 100)}% overlap).`);

    let realFlag = false;
    const mine = nameParts(p.name);
    const surname = mine[mine.length - 1];
    const text = `${p.name} ${p.summary}`.toLowerCase();
    for (const r of realParts) {
      if (!r.parts.length) continue;
      const rs = r.parts[r.parts.length - 1]!;
      if (surname && surname === rs) {
        realFlag = true;
        notes.push(`Shares a surname with a real office holder (${r.name}, ${r.country}).`);
      } else if (r.parts.length >= 2 && text.includes(`${r.parts[0]} ${rs}`)) {
        realFlag = true;
        notes.push(`Names a real office holder (${r.name}).`);
      } else if (r.bio.size >= 12 && jaccard(fingerprint(p), r.bio) >= t.bio) {
        realFlag = true;
        notes.push(`Reads too much like the record of a real office holder in ${r.country}.`);
      }
      if (realFlag) break;
    }

    const bad = (p.skills ?? []).filter((s) => !validSkillCodes.has(s.code)).length;
    if ((p.skills ?? []).length < 6) notes.push("Fewer than six skills.");
    if (bad) notes.push(`${bad} skill code(s) not in the taxonomy were dropped.`);

    return {
      slot: p.slot_index,
      ok: similarity < t.duplicate && !realFlag && (p.skills ?? []).length >= 6,
      similarity: Math.round(similarity * 100) / 100,
      nearest_slot: nearest,
      real_person_flag: realFlag,
      notes,
    };
  });
}

/** One-line digest of a persona, used so later batches avoid repeats. */
export function digest(
  p: Pick<PersonaRow, "slot_index" | "archetype" | "career_route" | "decision_style">,
): string {
  return `#${p.slot_index} ${p.archetype} — ${p.career_route}${p.decision_style?.style ? `; ${p.decision_style.style}` : ""}`;
}
