// Portfolio-level consolidation memo for Chamber 07 Stage 03.
// Rolls every synthesized study for a country into a single McKinsey-grade
// program brief that answers the original scope. Auto-generated by the
// auto-run pipeline once studies finish; also regenerable on demand.

import { useMutation, useQuery, useQueryClient, queryOptions } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { BookOpenCheck, Loader2, RefreshCw, Sparkles } from "lucide-react";

import { CitedMarkdown } from "@/components/citations/CitedMarkdown";
import { getStudyProgramReport, synthesizeStudyProgram } from "@/lib/personas/study.functions";

type ProgramSections = {
  portfolio_scope?: { studies_run?: number; brief_link?: string };
  cross_cutting_themes?: Array<{ label?: string; evidence_ids?: string[]; quote?: string }>;
  recommendations?: Array<{ move?: string; why?: string; owner?: string; horizon?: string }>;
  unanswered?: string[];
};

export function programReportQuery(code: string) {
  return queryOptions({
    queryKey: ["study-program-report", code],
    queryFn: () => getStudyProgramReport({ data: { countryCode: code } }),
    refetchInterval: 20_000,
  });
}

export function ProgramSynthesisCard({
  code,
  synthesizedCount,
}: {
  code: string;
  synthesizedCount: number;
}) {
  const qc = useQueryClient();
  const q = useQuery(programReportQuery(code));
  const runFn = useServerFn(synthesizeStudyProgram);
  const run = useMutation({
    mutationFn: () => runFn({ data: { countryCode: code } }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["study-program-report", code] }),
  });

  const report = q.data;
  const sections = (report?.sections ?? {}) as ProgramSections;
  const canGenerate = synthesizedCount >= 1;

  return (
    <section id="program-synthesis" className="border border-ink-950 bg-paper-0">
      <header className="flex flex-wrap items-center gap-3 border-b border-line-200 px-4 py-3">
        <span className="grid h-6 w-6 place-items-center border border-ink-950 bg-ink-950 text-paper-0">
          <BookOpenCheck size={12} />
        </span>
        <div className="min-w-0 flex-1">
          <p className="font-mono text-[10px] uppercase tracking-[0.22em] text-ink-500">
            Program synthesis · portfolio memo
          </p>
          <p className="font-serif text-lg leading-tight text-ink-950">
            {report ? "Consolidated across every study" : "Not yet consolidated"}
          </p>
        </div>
        <button
          type="button"
          onClick={() => run.mutate()}
          disabled={run.isPending || !canGenerate}
          className="inline-flex items-center gap-1.5 border border-ink-950 bg-ink-950 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[0.2em] text-paper-0 hover:bg-ink-700 disabled:opacity-40"
        >
          {run.isPending ? (
            <><Loader2 size={11} className="animate-spin" /> Consolidating…</>
          ) : report ? (
            <><RefreshCw size={11} /> Regenerate</>
          ) : (
            <><Sparkles size={11} /> Consolidate now</>
          )}
        </button>
      </header>

      {!canGenerate && !report && (
        <p className="px-4 py-6 text-sm text-ink-500">
          Once at least one study is synthesized, the program memo will consolidate every finding
          against the original brief.
        </p>
      )}

      {run.isError && (
        <p className="px-4 py-3 text-sm text-rose-600">{(run.error as Error).message}</p>
      )}

      {report && (
        <div className="grid gap-4 p-4 md:grid-cols-[minmax(0,1fr)_260px]">
          <div className="min-w-0">
            {report.summary_md && (
              <CitedMarkdown
                className="prose prose-sm max-w-none text-ink-800 [&_h2]:mt-4 [&_h2]:font-serif [&_h2]:text-sm [&_h2]:uppercase [&_h2]:tracking-[0.12em] [&_h2]:text-ink-500 [&_p]:my-2"
                source={report.summary_md}
                citations={(report.citations ?? []) as never}
              />
            )}
          </div>

          <aside className="space-y-4">
            {sections.portfolio_scope && (
              <div className="border border-line-200 bg-paper-100/40 px-3 py-2">
                <p className="font-mono text-[9px] uppercase tracking-[0.18em] text-ink-500">
                  Scope link
                </p>
                <p className="mt-1 text-[12px] text-ink-800">
                  {sections.portfolio_scope.brief_link ?? "—"}
                </p>
                <p className="mt-1 font-mono text-[10px] text-ink-500">
                  {sections.portfolio_scope.studies_run ?? 0} studies consolidated
                </p>
              </div>
            )}

            {Array.isArray(sections.recommendations) && sections.recommendations.length > 0 && (
              <div>
                <p className="font-mono text-[9px] uppercase tracking-[0.18em] text-ink-500">
                  Sovereign recommendations
                </p>
                <ul className="mt-2 space-y-2">
                  {sections.recommendations.slice(0, 6).map((r, i) => (
                    <li key={i} className="border border-line-200 px-3 py-2">
                      <p className="font-serif text-[13px] text-ink-950">{r.move ?? "—"}</p>
                      {r.why && <p className="mt-1 text-[11px] text-ink-700">{r.why}</p>}
                      <div className="mt-1 flex flex-wrap gap-1">
                        {r.owner && (
                          <span className="border border-line-200 px-1.5 py-0.5 font-mono text-[9px] uppercase tracking-[0.16em] text-ink-500">
                            {r.owner}
                          </span>
                        )}
                        {r.horizon && (
                          <span className="border border-line-200 px-1.5 py-0.5 font-mono text-[9px] uppercase tracking-[0.16em] text-ink-500">
                            {r.horizon}
                          </span>
                        )}
                      </div>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {Array.isArray(sections.unanswered) && sections.unanswered.length > 0 && (
              <div>
                <p className="font-mono text-[9px] uppercase tracking-[0.18em] text-ink-500">
                  Unanswered
                </p>
                <ul className="mt-1 space-y-1 text-[12px] text-ink-700">
                  {sections.unanswered.slice(0, 6).map((u, i) => (
                    <li key={i}>· {u}</li>
                  ))}
                </ul>
              </div>
            )}
          </aside>
        </div>
      )}
    </section>
  );
}
