import SHAPES from "./caribbean-shapes.json";

// Capital-city coordinates for every Caribbean country in the GDPVision
// country list. Shared by the regional map, globe and hazard-exposure rules.
export type GeoPoint = { code: string; name: string; lat: number; lon: number };

export const CARIBBEAN_POINTS: GeoPoint[] = [
  { code: "BHS", name: "The Bahamas", lat: 25.0343, lon: -77.3963 }, { code: "BLZ", name: "Belize", lat: 17.1899, lon: -88.4976 },
  { code: "JAM", name: "Jamaica", lat: 18.1096, lon: -77.2975 }, { code: "HTI", name: "Haiti", lat: 18.9712, lon: -72.2852 },
  { code: "KNA", name: "St. Kitts & Nevis", lat: 17.3578, lon: -62.783 }, { code: "AIA", name: "Anguilla", lat: 18.2206, lon: -63.0686 },
  { code: "ATG", name: "Antigua & Barbuda", lat: 17.0608, lon: -61.7964 }, { code: "DMA", name: "Dominica", lat: 15.415, lon: -61.371 },
  { code: "LCA", name: "Saint Lucia", lat: 13.9094, lon: -60.9789 }, { code: "VCT", name: "St. Vincent", lat: 13.2528, lon: -61.1971 },
  { code: "GRD", name: "Grenada", lat: 12.1165, lon: -61.679 }, { code: "BRB", name: "Barbados", lat: 13.1939, lon: -59.5432 },
  { code: "TTO", name: "Trinidad & Tobago", lat: 10.6918, lon: -61.2225 }, { code: "GUY", name: "Guyana", lat: 6.8013, lon: -58.1551 },
  { code: "SUR", name: "Suriname", lat: 5.852, lon: -55.2038 }, { code: "BMU", name: "Bermuda", lat: 32.3078, lon: -64.7505 },
  { code: "CYM", name: "Cayman Islands", lat: 19.2866, lon: -81.3744 }, { code: "TCA", name: "Turks & Caicos", lat: 21.4612, lon: -71.1419 },
  { code: "VGB", name: "British Virgin Islands", lat: 18.4286, lon: -64.6185 }, { code: "MSR", name: "Montserrat", lat: 16.7425, lon: -62.1874 },
  { code: "GLP", name: "Guadeloupe", lat: 16.265, lon: -61.551 }, { code: "MTQ", name: "Martinique", lat: 14.6415, lon: -61.0242 },
];

export const pointFor = (code: string) => CARIBBEAN_POINTS.find((p) => p.code === code.toUpperCase()) ?? null;


/** Outline rings ([lon,lat]) for a nation; generated by scripts/build-caribbean-shapes.ts from world-atlas 10m. */
export const shapeFor = (code: string): number[][][] => (SHAPES as Record<string, number[][][]>)[code.toUpperCase()] ?? [];

/**
 * SVG path for a nation's outline through any projection. When the projected
 * shape is smaller than `minSize` (in SVG units) it is enlarged around its own
 * centre so tiny islands stay visible — callers must label that "not to scale".
 */
export function shapePath(code: string, project: (lon: number, lat: number) => [number, number] | null, minSize: number) {
  const rings = shapeFor(code).map((r) => r.map(([lon, lat]) => project(lon, lat)).filter((p): p is [number, number] => !!p)).filter((r) => r.length >= 3);
  if (!rings.length) return null;
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  for (const r of rings) for (const [x, y] of r) { x0 = Math.min(x0, x); y0 = Math.min(y0, y); x1 = Math.max(x1, x); y1 = Math.max(y1, y); }
  const size = Math.max(x1 - x0, y1 - y0);
  const k = size > 0 && size < minSize ? minSize / size : 1;
  const cx = (x0 + x1) / 2, cy = (y0 + y1) / 2;
  const d = rings.map((r) => "M" + r.map(([x, y]) => `${(cx + (x - cx) * k).toFixed(2)},${(cy + (y - cy) * k).toFixed(2)}`).join("L") + "Z").join("");
  return { d, enlarged: k > 1, cx, cy, halfW: ((x1 - x0) * k) / 2 };
}
