/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KioskIndexRouteImport } from './routes/kiosk.index'
import { Route as KioskAdminRouteImport } from './routes/kiosk.admin'
import { Route as AuthenticatedInstrumentRouteRouteImport } from './routes/_authenticated/instrument/route'
import { Route as AuthenticatedInstrumentIndexRouteImport } from './routes/_authenticated/instrument/index'
import { Route as KioskApiUploadPresentationRouteImport } from './routes/kiosk.api.upload-presentation'
import { Route as KioskApiUploadMediaRouteImport } from './routes/kiosk.api.upload-media'
import { Route as KioskApiKioskDataRouteImport } from './routes/kiosk.api.kiosk-data'
import { Route as AuthenticatedInstrumentStewardshipRouteImport } from './routes/_authenticated/instrument/stewardship'
import { Route as AuthenticatedInstrumentExposureRouteImport } from './routes/_authenticated/instrument/exposure'
import { Route as AuthenticatedInstrumentScenariosIndexRouteImport } from './routes/_authenticated/instrument/scenarios.index'
import { Route as AuthenticatedInstrumentPortfolioIndexRouteImport } from './routes/_authenticated/instrument/portfolio.index'
import { Route as KioskApiPublicPresentationPdfRouteImport } from './routes/kiosk.api.public.presentation-pdf'
import { Route as AuthenticatedInstrumentSectorCodeRouteImport } from './routes/_authenticated/instrument/sector.$code'
import { Route as AuthenticatedInstrumentScenariosNewRouteImport } from './routes/_authenticated/instrument/scenarios.new'
import { Route as AuthenticatedInstrumentScenariosIdRouteImport } from './routes/_authenticated/instrument/scenarios.$id'
import { Route as AuthenticatedInstrumentPortfolioMinistryRouteImport } from './routes/_authenticated/instrument/portfolio.$ministry'

const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskIndexRoute = KioskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KioskRoute,
} as any)
const KioskAdminRoute = KioskAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => KioskRoute,
} as any)
const AuthenticatedInstrumentRouteRoute =
  AuthenticatedInstrumentRouteRouteImport.update({
    id: '/instrument',
    path: '/instrument',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstrumentIndexRoute =
  AuthenticatedInstrumentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const KioskApiUploadPresentationRoute =
  KioskApiUploadPresentationRouteImport.update({
    id: '/api/upload-presentation',
    path: '/api/upload-presentation',
    getParentRoute: () => KioskRoute,
  } as any)
const KioskApiUploadMediaRoute = KioskApiUploadMediaRouteImport.update({
  id: '/api/upload-media',
  path: '/api/upload-media',
  getParentRoute: () => KioskRoute,
} as any)
const KioskApiKioskDataRoute = KioskApiKioskDataRouteImport.update({
  id: '/api/kiosk-data',
  path: '/api/kiosk-data',
  getParentRoute: () => KioskRoute,
} as any)
const AuthenticatedInstrumentStewardshipRoute =
  AuthenticatedInstrumentStewardshipRouteImport.update({
    id: '/stewardship',
    path: '/stewardship',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentExposureRoute =
  AuthenticatedInstrumentExposureRouteImport.update({
    id: '/exposure',
    path: '/exposure',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentScenariosIndexRoute =
  AuthenticatedInstrumentScenariosIndexRouteImport.update({
    id: '/scenarios/',
    path: '/scenarios/',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentPortfolioIndexRoute =
  AuthenticatedInstrumentPortfolioIndexRouteImport.update({
    id: '/portfolio/',
    path: '/portfolio/',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const KioskApiPublicPresentationPdfRoute =
  KioskApiPublicPresentationPdfRouteImport.update({
    id: '/api/public/presentation-pdf',
    path: '/api/public/presentation-pdf',
    getParentRoute: () => KioskRoute,
  } as any)
const AuthenticatedInstrumentSectorCodeRoute =
  AuthenticatedInstrumentSectorCodeRouteImport.update({
    id: '/sector/$code',
    path: '/sector/$code',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentScenariosNewRoute =
  AuthenticatedInstrumentScenariosNewRouteImport.update({
    id: '/scenarios/new',
    path: '/scenarios/new',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentScenariosIdRoute =
  AuthenticatedInstrumentScenariosIdRouteImport.update({
    id: '/scenarios/$id',
    path: '/scenarios/$id',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentPortfolioMinistryRoute =
  AuthenticatedInstrumentPortfolioMinistryRouteImport.update({
    id: '/portfolio/$ministry',
    path: '/portfolio/$ministry',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRouteWithChildren
  '/instrument': typeof AuthenticatedInstrumentRouteRouteWithChildren
  '/kiosk/admin': typeof KioskAdminRoute
  '/kiosk/': typeof KioskIndexRoute
  '/instrument/exposure': typeof AuthenticatedInstrumentExposureRoute
  '/instrument/stewardship': typeof AuthenticatedInstrumentStewardshipRoute
  '/kiosk/api/kiosk-data': typeof KioskApiKioskDataRoute
  '/kiosk/api/upload-media': typeof KioskApiUploadMediaRoute
  '/kiosk/api/upload-presentation': typeof KioskApiUploadPresentationRoute
  '/instrument/': typeof AuthenticatedInstrumentIndexRoute
  '/instrument/portfolio/$ministry': typeof AuthenticatedInstrumentPortfolioMinistryRoute
  '/instrument/scenarios/$id': typeof AuthenticatedInstrumentScenariosIdRoute
  '/instrument/scenarios/new': typeof AuthenticatedInstrumentScenariosNewRoute
  '/instrument/sector/$code': typeof AuthenticatedInstrumentSectorCodeRoute
  '/kiosk/api/public/presentation-pdf': typeof KioskApiPublicPresentationPdfRoute
  '/instrument/portfolio/': typeof AuthenticatedInstrumentPortfolioIndexRoute
  '/instrument/scenarios/': typeof AuthenticatedInstrumentScenariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kiosk/admin': typeof KioskAdminRoute
  '/kiosk': typeof KioskIndexRoute
  '/instrument/exposure': typeof AuthenticatedInstrumentExposureRoute
  '/instrument/stewardship': typeof AuthenticatedInstrumentStewardshipRoute
  '/kiosk/api/kiosk-data': typeof KioskApiKioskDataRoute
  '/kiosk/api/upload-media': typeof KioskApiUploadMediaRoute
  '/kiosk/api/upload-presentation': typeof KioskApiUploadPresentationRoute
  '/instrument': typeof AuthenticatedInstrumentIndexRoute
  '/instrument/portfolio/$ministry': typeof AuthenticatedInstrumentPortfolioMinistryRoute
  '/instrument/scenarios/$id': typeof AuthenticatedInstrumentScenariosIdRoute
  '/instrument/scenarios/new': typeof AuthenticatedInstrumentScenariosNewRoute
  '/instrument/sector/$code': typeof AuthenticatedInstrumentSectorCodeRoute
  '/kiosk/api/public/presentation-pdf': typeof KioskApiPublicPresentationPdfRoute
  '/instrument/portfolio': typeof AuthenticatedInstrumentPortfolioIndexRoute
  '/instrument/scenarios': typeof AuthenticatedInstrumentScenariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRouteWithChildren
  '/_authenticated/instrument': typeof AuthenticatedInstrumentRouteRouteWithChildren
  '/kiosk/admin': typeof KioskAdminRoute
  '/kiosk/': typeof KioskIndexRoute
  '/_authenticated/instrument/exposure': typeof AuthenticatedInstrumentExposureRoute
  '/_authenticated/instrument/stewardship': typeof AuthenticatedInstrumentStewardshipRoute
  '/kiosk/api/kiosk-data': typeof KioskApiKioskDataRoute
  '/kiosk/api/upload-media': typeof KioskApiUploadMediaRoute
  '/kiosk/api/upload-presentation': typeof KioskApiUploadPresentationRoute
  '/_authenticated/instrument/': typeof AuthenticatedInstrumentIndexRoute
  '/_authenticated/instrument/portfolio/$ministry': typeof AuthenticatedInstrumentPortfolioMinistryRoute
  '/_authenticated/instrument/scenarios/$id': typeof AuthenticatedInstrumentScenariosIdRoute
  '/_authenticated/instrument/scenarios/new': typeof AuthenticatedInstrumentScenariosNewRoute
  '/_authenticated/instrument/sector/$code': typeof AuthenticatedInstrumentSectorCodeRoute
  '/kiosk/api/public/presentation-pdf': typeof KioskApiPublicPresentationPdfRoute
  '/_authenticated/instrument/portfolio/': typeof AuthenticatedInstrumentPortfolioIndexRoute
  '/_authenticated/instrument/scenarios/': typeof AuthenticatedInstrumentScenariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kiosk'
    | '/instrument'
    | '/kiosk/admin'
    | '/kiosk/'
    | '/instrument/exposure'
    | '/instrument/stewardship'
    | '/kiosk/api/kiosk-data'
    | '/kiosk/api/upload-media'
    | '/kiosk/api/upload-presentation'
    | '/instrument/'
    | '/instrument/portfolio/$ministry'
    | '/instrument/scenarios/$id'
    | '/instrument/scenarios/new'
    | '/instrument/sector/$code'
    | '/kiosk/api/public/presentation-pdf'
    | '/instrument/portfolio/'
    | '/instrument/scenarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kiosk/admin'
    | '/kiosk'
    | '/instrument/exposure'
    | '/instrument/stewardship'
    | '/kiosk/api/kiosk-data'
    | '/kiosk/api/upload-media'
    | '/kiosk/api/upload-presentation'
    | '/instrument'
    | '/instrument/portfolio/$ministry'
    | '/instrument/scenarios/$id'
    | '/instrument/scenarios/new'
    | '/instrument/sector/$code'
    | '/kiosk/api/public/presentation-pdf'
    | '/instrument/portfolio'
    | '/instrument/scenarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kiosk'
    | '/_authenticated/instrument'
    | '/kiosk/admin'
    | '/kiosk/'
    | '/_authenticated/instrument/exposure'
    | '/_authenticated/instrument/stewardship'
    | '/kiosk/api/kiosk-data'
    | '/kiosk/api/upload-media'
    | '/kiosk/api/upload-presentation'
    | '/_authenticated/instrument/'
    | '/_authenticated/instrument/portfolio/$ministry'
    | '/_authenticated/instrument/scenarios/$id'
    | '/_authenticated/instrument/scenarios/new'
    | '/_authenticated/instrument/sector/$code'
    | '/kiosk/api/public/presentation-pdf'
    | '/_authenticated/instrument/portfolio/'
    | '/_authenticated/instrument/scenarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KioskRoute: typeof KioskRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/': {
      id: '/kiosk/'
      path: '/'
      fullPath: '/kiosk/'
      preLoaderRoute: typeof KioskIndexRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/admin': {
      id: '/kiosk/admin'
      path: '/admin'
      fullPath: '/kiosk/admin'
      preLoaderRoute: typeof KioskAdminRouteImport
      parentRoute: typeof KioskRoute
    }
    '/_authenticated/instrument': {
      id: '/_authenticated/instrument'
      path: '/instrument'
      fullPath: '/instrument'
      preLoaderRoute: typeof AuthenticatedInstrumentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instrument/': {
      id: '/_authenticated/instrument/'
      path: '/'
      fullPath: '/instrument/'
      preLoaderRoute: typeof AuthenticatedInstrumentIndexRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/kiosk/api/upload-presentation': {
      id: '/kiosk/api/upload-presentation'
      path: '/api/upload-presentation'
      fullPath: '/kiosk/api/upload-presentation'
      preLoaderRoute: typeof KioskApiUploadPresentationRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/api/upload-media': {
      id: '/kiosk/api/upload-media'
      path: '/api/upload-media'
      fullPath: '/kiosk/api/upload-media'
      preLoaderRoute: typeof KioskApiUploadMediaRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/api/kiosk-data': {
      id: '/kiosk/api/kiosk-data'
      path: '/api/kiosk-data'
      fullPath: '/kiosk/api/kiosk-data'
      preLoaderRoute: typeof KioskApiKioskDataRouteImport
      parentRoute: typeof KioskRoute
    }
    '/_authenticated/instrument/stewardship': {
      id: '/_authenticated/instrument/stewardship'
      path: '/stewardship'
      fullPath: '/instrument/stewardship'
      preLoaderRoute: typeof AuthenticatedInstrumentStewardshipRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/exposure': {
      id: '/_authenticated/instrument/exposure'
      path: '/exposure'
      fullPath: '/instrument/exposure'
      preLoaderRoute: typeof AuthenticatedInstrumentExposureRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/scenarios/': {
      id: '/_authenticated/instrument/scenarios/'
      path: '/scenarios'
      fullPath: '/instrument/scenarios/'
      preLoaderRoute: typeof AuthenticatedInstrumentScenariosIndexRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/portfolio/': {
      id: '/_authenticated/instrument/portfolio/'
      path: '/portfolio'
      fullPath: '/instrument/portfolio/'
      preLoaderRoute: typeof AuthenticatedInstrumentPortfolioIndexRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/kiosk/api/public/presentation-pdf': {
      id: '/kiosk/api/public/presentation-pdf'
      path: '/api/public/presentation-pdf'
      fullPath: '/kiosk/api/public/presentation-pdf'
      preLoaderRoute: typeof KioskApiPublicPresentationPdfRouteImport
      parentRoute: typeof KioskRoute
    }
    '/_authenticated/instrument/sector/$code': {
      id: '/_authenticated/instrument/sector/$code'
      path: '/sector/$code'
      fullPath: '/instrument/sector/$code'
      preLoaderRoute: typeof AuthenticatedInstrumentSectorCodeRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/scenarios/new': {
      id: '/_authenticated/instrument/scenarios/new'
      path: '/scenarios/new'
      fullPath: '/instrument/scenarios/new'
      preLoaderRoute: typeof AuthenticatedInstrumentScenariosNewRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/scenarios/$id': {
      id: '/_authenticated/instrument/scenarios/$id'
      path: '/scenarios/$id'
      fullPath: '/instrument/scenarios/$id'
      preLoaderRoute: typeof AuthenticatedInstrumentScenariosIdRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/portfolio/$ministry': {
      id: '/_authenticated/instrument/portfolio/$ministry'
      path: '/portfolio/$ministry'
      fullPath: '/instrument/portfolio/$ministry'
      preLoaderRoute: typeof AuthenticatedInstrumentPortfolioMinistryRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
  }
}

interface AuthenticatedInstrumentRouteRouteChildren {
  AuthenticatedInstrumentExposureRoute: typeof AuthenticatedInstrumentExposureRoute
  AuthenticatedInstrumentStewardshipRoute: typeof AuthenticatedInstrumentStewardshipRoute
  AuthenticatedInstrumentIndexRoute: typeof AuthenticatedInstrumentIndexRoute
  AuthenticatedInstrumentPortfolioMinistryRoute: typeof AuthenticatedInstrumentPortfolioMinistryRoute
  AuthenticatedInstrumentScenariosIdRoute: typeof AuthenticatedInstrumentScenariosIdRoute
  AuthenticatedInstrumentScenariosNewRoute: typeof AuthenticatedInstrumentScenariosNewRoute
  AuthenticatedInstrumentSectorCodeRoute: typeof AuthenticatedInstrumentSectorCodeRoute
  AuthenticatedInstrumentPortfolioIndexRoute: typeof AuthenticatedInstrumentPortfolioIndexRoute
  AuthenticatedInstrumentScenariosIndexRoute: typeof AuthenticatedInstrumentScenariosIndexRoute
}

const AuthenticatedInstrumentRouteRouteChildren: AuthenticatedInstrumentRouteRouteChildren =
  {
    AuthenticatedInstrumentExposureRoute: AuthenticatedInstrumentExposureRoute,
    AuthenticatedInstrumentStewardshipRoute:
      AuthenticatedInstrumentStewardshipRoute,
    AuthenticatedInstrumentIndexRoute: AuthenticatedInstrumentIndexRoute,
    AuthenticatedInstrumentPortfolioMinistryRoute:
      AuthenticatedInstrumentPortfolioMinistryRoute,
    AuthenticatedInstrumentScenariosIdRoute:
      AuthenticatedInstrumentScenariosIdRoute,
    AuthenticatedInstrumentScenariosNewRoute:
      AuthenticatedInstrumentScenariosNewRoute,
    AuthenticatedInstrumentSectorCodeRoute:
      AuthenticatedInstrumentSectorCodeRoute,
    AuthenticatedInstrumentPortfolioIndexRoute:
      AuthenticatedInstrumentPortfolioIndexRoute,
    AuthenticatedInstrumentScenariosIndexRoute:
      AuthenticatedInstrumentScenariosIndexRoute,
  }

const AuthenticatedInstrumentRouteRouteWithChildren =
  AuthenticatedInstrumentRouteRoute._addFileChildren(
    AuthenticatedInstrumentRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInstrumentRouteRoute: typeof AuthenticatedInstrumentRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInstrumentRouteRoute:
    AuthenticatedInstrumentRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface KioskRouteChildren {
  KioskAdminRoute: typeof KioskAdminRoute
  KioskIndexRoute: typeof KioskIndexRoute
  KioskApiKioskDataRoute: typeof KioskApiKioskDataRoute
  KioskApiUploadMediaRoute: typeof KioskApiUploadMediaRoute
  KioskApiUploadPresentationRoute: typeof KioskApiUploadPresentationRoute
  KioskApiPublicPresentationPdfRoute: typeof KioskApiPublicPresentationPdfRoute
}

const KioskRouteChildren: KioskRouteChildren = {
  KioskAdminRoute: KioskAdminRoute,
  KioskIndexRoute: KioskIndexRoute,
  KioskApiKioskDataRoute: KioskApiKioskDataRoute,
  KioskApiUploadMediaRoute: KioskApiUploadMediaRoute,
  KioskApiUploadPresentationRoute: KioskApiUploadPresentationRoute,
  KioskApiPublicPresentationPdfRoute: KioskApiPublicPresentationPdfRoute,
}

const KioskRouteWithChildren = KioskRoute._addFileChildren(KioskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KioskRoute: KioskRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
