/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadPresentationRouteImport } from './routes/api/upload-presentation'
import { Route as ApiUploadMediaRouteImport } from './routes/api/upload-media'
import { Route as ApiKioskDataRouteImport } from './routes/api/kiosk-data'
import { Route as ApiPublicPresentationPdfRouteImport } from './routes/api/public/presentation-pdf'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadPresentationRoute = ApiUploadPresentationRouteImport.update({
  id: '/api/upload-presentation',
  path: '/api/upload-presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadMediaRoute = ApiUploadMediaRouteImport.update({
  id: '/api/upload-media',
  path: '/api/upload-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKioskDataRoute = ApiKioskDataRouteImport.update({
  id: '/api/kiosk-data',
  path: '/api/kiosk-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPresentationPdfRoute =
  ApiPublicPresentationPdfRouteImport.update({
    id: '/api/public/presentation-pdf',
    path: '/api/public/presentation-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/kiosk-data': typeof ApiKioskDataRoute
  '/api/upload-media': typeof ApiUploadMediaRoute
  '/api/upload-presentation': typeof ApiUploadPresentationRoute
  '/api/public/presentation-pdf': typeof ApiPublicPresentationPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/kiosk-data': typeof ApiKioskDataRoute
  '/api/upload-media': typeof ApiUploadMediaRoute
  '/api/upload-presentation': typeof ApiUploadPresentationRoute
  '/api/public/presentation-pdf': typeof ApiPublicPresentationPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/kiosk-data': typeof ApiKioskDataRoute
  '/api/upload-media': typeof ApiUploadMediaRoute
  '/api/upload-presentation': typeof ApiUploadPresentationRoute
  '/api/public/presentation-pdf': typeof ApiPublicPresentationPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/kiosk-data'
    | '/api/upload-media'
    | '/api/upload-presentation'
    | '/api/public/presentation-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/kiosk-data'
    | '/api/upload-media'
    | '/api/upload-presentation'
    | '/api/public/presentation-pdf'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/kiosk-data'
    | '/api/upload-media'
    | '/api/upload-presentation'
    | '/api/public/presentation-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiKioskDataRoute: typeof ApiKioskDataRoute
  ApiUploadMediaRoute: typeof ApiUploadMediaRoute
  ApiUploadPresentationRoute: typeof ApiUploadPresentationRoute
  ApiPublicPresentationPdfRoute: typeof ApiPublicPresentationPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-presentation': {
      id: '/api/upload-presentation'
      path: '/api/upload-presentation'
      fullPath: '/api/upload-presentation'
      preLoaderRoute: typeof ApiUploadPresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-media': {
      id: '/api/upload-media'
      path: '/api/upload-media'
      fullPath: '/api/upload-media'
      preLoaderRoute: typeof ApiUploadMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kiosk-data': {
      id: '/api/kiosk-data'
      path: '/api/kiosk-data'
      fullPath: '/api/kiosk-data'
      preLoaderRoute: typeof ApiKioskDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/presentation-pdf': {
      id: '/api/public/presentation-pdf'
      path: '/api/public/presentation-pdf'
      fullPath: '/api/public/presentation-pdf'
      preLoaderRoute: typeof ApiPublicPresentationPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiKioskDataRoute: ApiKioskDataRoute,
  ApiUploadMediaRoute: ApiUploadMediaRoute,
  ApiUploadPresentationRoute: ApiUploadPresentationRoute,
  ApiPublicPresentationPdfRoute: ApiPublicPresentationPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
