/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KioskIndexRouteImport } from './routes/kiosk.index'
import { Route as KioskAdminRouteImport } from './routes/kiosk.admin'
import { Route as AuthenticatedNarrativeRouteRouteImport } from './routes/_authenticated/narrative/route'
import { Route as AuthenticatedInstrumentRouteRouteImport } from './routes/_authenticated/instrument/route'
import { Route as AuthenticatedNarrativeIndexRouteImport } from './routes/_authenticated/narrative/index'
import { Route as AuthenticatedInstrumentIndexRouteImport } from './routes/_authenticated/instrument/index'
import { Route as AuthenticatedCounselIndexRouteImport } from './routes/_authenticated/counsel/index'
import { Route as KioskApiUploadPresentationRouteImport } from './routes/kiosk.api.upload-presentation'
import { Route as KioskApiUploadMediaRouteImport } from './routes/kiosk.api.upload-media'
import { Route as KioskApiKioskDataRouteImport } from './routes/kiosk.api.kiosk-data'
import { Route as AuthenticatedNarrativeQueueRouteImport } from './routes/_authenticated/narrative/queue'
import { Route as AuthenticatedNarrativeIngestRouteImport } from './routes/_authenticated/narrative/ingest'
import { Route as AuthenticatedNarrativeCommsRouteImport } from './routes/_authenticated/narrative/comms'
import { Route as AuthenticatedNarrativeBrainRouteImport } from './routes/_authenticated/narrative/brain'
import { Route as AuthenticatedInstrumentStewardshipRouteImport } from './routes/_authenticated/instrument/stewardship'
import { Route as AuthenticatedInstrumentExposureRouteImport } from './routes/_authenticated/instrument/exposure'
import { Route as AuthenticatedNarrativeStrategyIndexRouteImport } from './routes/_authenticated/narrative/strategy.index'
import { Route as AuthenticatedInstrumentScenariosIndexRouteImport } from './routes/_authenticated/instrument/scenarios.index'
import { Route as AuthenticatedInstrumentPortfolioIndexRouteImport } from './routes/_authenticated/instrument/portfolio.index'
import { Route as AuthenticatedInstrumentCabinetIndexRouteImport } from './routes/_authenticated/instrument/cabinet.index'
import { Route as KioskApiPublicPresentationPdfRouteImport } from './routes/kiosk.api.public.presentation-pdf'
import { Route as ApiPublicHooksNarrativeHarvestRouteImport } from './routes/api/public/hooks/narrative-harvest'
import { Route as AuthenticatedInstrumentStudioPackagesRouteImport } from './routes/_authenticated/instrument/studio.packages'
import { Route as AuthenticatedInstrumentStudioGapRouteImport } from './routes/_authenticated/instrument/studio.gap'
import { Route as AuthenticatedInstrumentSectorCodeRouteImport } from './routes/_authenticated/instrument/sector.$code'
import { Route as AuthenticatedInstrumentScenariosNewRouteImport } from './routes/_authenticated/instrument/scenarios.new'
import { Route as AuthenticatedInstrumentScenariosCompareRouteImport } from './routes/_authenticated/instrument/scenarios.compare'
import { Route as AuthenticatedInstrumentScenariosIdRouteImport } from './routes/_authenticated/instrument/scenarios.$id'
import { Route as AuthenticatedInstrumentPortfolioMinistryRouteImport } from './routes/_authenticated/instrument/portfolio.$ministry'
import { Route as AuthenticatedInstrumentMandateStudioRouteImport } from './routes/_authenticated/instrument/mandate.studio'
import { Route as AuthenticatedInstrumentMandateScorecardRouteImport } from './routes/_authenticated/instrument/mandate.scorecard'
import { Route as AuthenticatedInstrumentCabinetSessionRouteImport } from './routes/_authenticated/instrument/cabinet.session'

const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskIndexRoute = KioskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KioskRoute,
} as any)
const KioskAdminRoute = KioskAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => KioskRoute,
} as any)
const AuthenticatedNarrativeRouteRoute =
  AuthenticatedNarrativeRouteRouteImport.update({
    id: '/narrative',
    path: '/narrative',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstrumentRouteRoute =
  AuthenticatedInstrumentRouteRouteImport.update({
    id: '/instrument',
    path: '/instrument',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNarrativeIndexRoute =
  AuthenticatedNarrativeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNarrativeRouteRoute,
  } as any)
const AuthenticatedInstrumentIndexRoute =
  AuthenticatedInstrumentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedCounselIndexRoute =
  AuthenticatedCounselIndexRouteImport.update({
    id: '/counsel/',
    path: '/counsel/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const KioskApiUploadPresentationRoute =
  KioskApiUploadPresentationRouteImport.update({
    id: '/api/upload-presentation',
    path: '/api/upload-presentation',
    getParentRoute: () => KioskRoute,
  } as any)
const KioskApiUploadMediaRoute = KioskApiUploadMediaRouteImport.update({
  id: '/api/upload-media',
  path: '/api/upload-media',
  getParentRoute: () => KioskRoute,
} as any)
const KioskApiKioskDataRoute = KioskApiKioskDataRouteImport.update({
  id: '/api/kiosk-data',
  path: '/api/kiosk-data',
  getParentRoute: () => KioskRoute,
} as any)
const AuthenticatedNarrativeQueueRoute =
  AuthenticatedNarrativeQueueRouteImport.update({
    id: '/queue',
    path: '/queue',
    getParentRoute: () => AuthenticatedNarrativeRouteRoute,
  } as any)
const AuthenticatedNarrativeIngestRoute =
  AuthenticatedNarrativeIngestRouteImport.update({
    id: '/ingest',
    path: '/ingest',
    getParentRoute: () => AuthenticatedNarrativeRouteRoute,
  } as any)
const AuthenticatedNarrativeCommsRoute =
  AuthenticatedNarrativeCommsRouteImport.update({
    id: '/comms',
    path: '/comms',
    getParentRoute: () => AuthenticatedNarrativeRouteRoute,
  } as any)
const AuthenticatedNarrativeBrainRoute =
  AuthenticatedNarrativeBrainRouteImport.update({
    id: '/brain',
    path: '/brain',
    getParentRoute: () => AuthenticatedNarrativeRouteRoute,
  } as any)
const AuthenticatedInstrumentStewardshipRoute =
  AuthenticatedInstrumentStewardshipRouteImport.update({
    id: '/stewardship',
    path: '/stewardship',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentExposureRoute =
  AuthenticatedInstrumentExposureRouteImport.update({
    id: '/exposure',
    path: '/exposure',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedNarrativeStrategyIndexRoute =
  AuthenticatedNarrativeStrategyIndexRouteImport.update({
    id: '/strategy/',
    path: '/strategy/',
    getParentRoute: () => AuthenticatedNarrativeRouteRoute,
  } as any)
const AuthenticatedInstrumentScenariosIndexRoute =
  AuthenticatedInstrumentScenariosIndexRouteImport.update({
    id: '/scenarios/',
    path: '/scenarios/',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentPortfolioIndexRoute =
  AuthenticatedInstrumentPortfolioIndexRouteImport.update({
    id: '/portfolio/',
    path: '/portfolio/',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentCabinetIndexRoute =
  AuthenticatedInstrumentCabinetIndexRouteImport.update({
    id: '/cabinet/',
    path: '/cabinet/',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const KioskApiPublicPresentationPdfRoute =
  KioskApiPublicPresentationPdfRouteImport.update({
    id: '/api/public/presentation-pdf',
    path: '/api/public/presentation-pdf',
    getParentRoute: () => KioskRoute,
  } as any)
const ApiPublicHooksNarrativeHarvestRoute =
  ApiPublicHooksNarrativeHarvestRouteImport.update({
    id: '/api/public/hooks/narrative-harvest',
    path: '/api/public/hooks/narrative-harvest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInstrumentStudioPackagesRoute =
  AuthenticatedInstrumentStudioPackagesRouteImport.update({
    id: '/studio/packages',
    path: '/studio/packages',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentStudioGapRoute =
  AuthenticatedInstrumentStudioGapRouteImport.update({
    id: '/studio/gap',
    path: '/studio/gap',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentSectorCodeRoute =
  AuthenticatedInstrumentSectorCodeRouteImport.update({
    id: '/sector/$code',
    path: '/sector/$code',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentScenariosNewRoute =
  AuthenticatedInstrumentScenariosNewRouteImport.update({
    id: '/scenarios/new',
    path: '/scenarios/new',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentScenariosCompareRoute =
  AuthenticatedInstrumentScenariosCompareRouteImport.update({
    id: '/scenarios/compare',
    path: '/scenarios/compare',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentScenariosIdRoute =
  AuthenticatedInstrumentScenariosIdRouteImport.update({
    id: '/scenarios/$id',
    path: '/scenarios/$id',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentPortfolioMinistryRoute =
  AuthenticatedInstrumentPortfolioMinistryRouteImport.update({
    id: '/portfolio/$ministry',
    path: '/portfolio/$ministry',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentMandateStudioRoute =
  AuthenticatedInstrumentMandateStudioRouteImport.update({
    id: '/mandate/studio',
    path: '/mandate/studio',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentMandateScorecardRoute =
  AuthenticatedInstrumentMandateScorecardRouteImport.update({
    id: '/mandate/scorecard',
    path: '/mandate/scorecard',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)
const AuthenticatedInstrumentCabinetSessionRoute =
  AuthenticatedInstrumentCabinetSessionRouteImport.update({
    id: '/cabinet/session',
    path: '/cabinet/session',
    getParentRoute: () => AuthenticatedInstrumentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRouteWithChildren
  '/instrument': typeof AuthenticatedInstrumentRouteRouteWithChildren
  '/narrative': typeof AuthenticatedNarrativeRouteRouteWithChildren
  '/kiosk/admin': typeof KioskAdminRoute
  '/kiosk/': typeof KioskIndexRoute
  '/instrument/exposure': typeof AuthenticatedInstrumentExposureRoute
  '/instrument/stewardship': typeof AuthenticatedInstrumentStewardshipRoute
  '/narrative/brain': typeof AuthenticatedNarrativeBrainRoute
  '/narrative/comms': typeof AuthenticatedNarrativeCommsRoute
  '/narrative/ingest': typeof AuthenticatedNarrativeIngestRoute
  '/narrative/queue': typeof AuthenticatedNarrativeQueueRoute
  '/kiosk/api/kiosk-data': typeof KioskApiKioskDataRoute
  '/kiosk/api/upload-media': typeof KioskApiUploadMediaRoute
  '/kiosk/api/upload-presentation': typeof KioskApiUploadPresentationRoute
  '/counsel/': typeof AuthenticatedCounselIndexRoute
  '/instrument/': typeof AuthenticatedInstrumentIndexRoute
  '/narrative/': typeof AuthenticatedNarrativeIndexRoute
  '/instrument/cabinet/session': typeof AuthenticatedInstrumentCabinetSessionRoute
  '/instrument/mandate/scorecard': typeof AuthenticatedInstrumentMandateScorecardRoute
  '/instrument/mandate/studio': typeof AuthenticatedInstrumentMandateStudioRoute
  '/instrument/portfolio/$ministry': typeof AuthenticatedInstrumentPortfolioMinistryRoute
  '/instrument/scenarios/$id': typeof AuthenticatedInstrumentScenariosIdRoute
  '/instrument/scenarios/compare': typeof AuthenticatedInstrumentScenariosCompareRoute
  '/instrument/scenarios/new': typeof AuthenticatedInstrumentScenariosNewRoute
  '/instrument/sector/$code': typeof AuthenticatedInstrumentSectorCodeRoute
  '/instrument/studio/gap': typeof AuthenticatedInstrumentStudioGapRoute
  '/instrument/studio/packages': typeof AuthenticatedInstrumentStudioPackagesRoute
  '/api/public/hooks/narrative-harvest': typeof ApiPublicHooksNarrativeHarvestRoute
  '/kiosk/api/public/presentation-pdf': typeof KioskApiPublicPresentationPdfRoute
  '/instrument/cabinet/': typeof AuthenticatedInstrumentCabinetIndexRoute
  '/instrument/portfolio/': typeof AuthenticatedInstrumentPortfolioIndexRoute
  '/instrument/scenarios/': typeof AuthenticatedInstrumentScenariosIndexRoute
  '/narrative/strategy/': typeof AuthenticatedNarrativeStrategyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kiosk/admin': typeof KioskAdminRoute
  '/kiosk': typeof KioskIndexRoute
  '/instrument/exposure': typeof AuthenticatedInstrumentExposureRoute
  '/instrument/stewardship': typeof AuthenticatedInstrumentStewardshipRoute
  '/narrative/brain': typeof AuthenticatedNarrativeBrainRoute
  '/narrative/comms': typeof AuthenticatedNarrativeCommsRoute
  '/narrative/ingest': typeof AuthenticatedNarrativeIngestRoute
  '/narrative/queue': typeof AuthenticatedNarrativeQueueRoute
  '/kiosk/api/kiosk-data': typeof KioskApiKioskDataRoute
  '/kiosk/api/upload-media': typeof KioskApiUploadMediaRoute
  '/kiosk/api/upload-presentation': typeof KioskApiUploadPresentationRoute
  '/counsel': typeof AuthenticatedCounselIndexRoute
  '/instrument': typeof AuthenticatedInstrumentIndexRoute
  '/narrative': typeof AuthenticatedNarrativeIndexRoute
  '/instrument/cabinet/session': typeof AuthenticatedInstrumentCabinetSessionRoute
  '/instrument/mandate/scorecard': typeof AuthenticatedInstrumentMandateScorecardRoute
  '/instrument/mandate/studio': typeof AuthenticatedInstrumentMandateStudioRoute
  '/instrument/portfolio/$ministry': typeof AuthenticatedInstrumentPortfolioMinistryRoute
  '/instrument/scenarios/$id': typeof AuthenticatedInstrumentScenariosIdRoute
  '/instrument/scenarios/compare': typeof AuthenticatedInstrumentScenariosCompareRoute
  '/instrument/scenarios/new': typeof AuthenticatedInstrumentScenariosNewRoute
  '/instrument/sector/$code': typeof AuthenticatedInstrumentSectorCodeRoute
  '/instrument/studio/gap': typeof AuthenticatedInstrumentStudioGapRoute
  '/instrument/studio/packages': typeof AuthenticatedInstrumentStudioPackagesRoute
  '/api/public/hooks/narrative-harvest': typeof ApiPublicHooksNarrativeHarvestRoute
  '/kiosk/api/public/presentation-pdf': typeof KioskApiPublicPresentationPdfRoute
  '/instrument/cabinet': typeof AuthenticatedInstrumentCabinetIndexRoute
  '/instrument/portfolio': typeof AuthenticatedInstrumentPortfolioIndexRoute
  '/instrument/scenarios': typeof AuthenticatedInstrumentScenariosIndexRoute
  '/narrative/strategy': typeof AuthenticatedNarrativeStrategyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRouteWithChildren
  '/_authenticated/instrument': typeof AuthenticatedInstrumentRouteRouteWithChildren
  '/_authenticated/narrative': typeof AuthenticatedNarrativeRouteRouteWithChildren
  '/kiosk/admin': typeof KioskAdminRoute
  '/kiosk/': typeof KioskIndexRoute
  '/_authenticated/instrument/exposure': typeof AuthenticatedInstrumentExposureRoute
  '/_authenticated/instrument/stewardship': typeof AuthenticatedInstrumentStewardshipRoute
  '/_authenticated/narrative/brain': typeof AuthenticatedNarrativeBrainRoute
  '/_authenticated/narrative/comms': typeof AuthenticatedNarrativeCommsRoute
  '/_authenticated/narrative/ingest': typeof AuthenticatedNarrativeIngestRoute
  '/_authenticated/narrative/queue': typeof AuthenticatedNarrativeQueueRoute
  '/kiosk/api/kiosk-data': typeof KioskApiKioskDataRoute
  '/kiosk/api/upload-media': typeof KioskApiUploadMediaRoute
  '/kiosk/api/upload-presentation': typeof KioskApiUploadPresentationRoute
  '/_authenticated/counsel/': typeof AuthenticatedCounselIndexRoute
  '/_authenticated/instrument/': typeof AuthenticatedInstrumentIndexRoute
  '/_authenticated/narrative/': typeof AuthenticatedNarrativeIndexRoute
  '/_authenticated/instrument/cabinet/session': typeof AuthenticatedInstrumentCabinetSessionRoute
  '/_authenticated/instrument/mandate/scorecard': typeof AuthenticatedInstrumentMandateScorecardRoute
  '/_authenticated/instrument/mandate/studio': typeof AuthenticatedInstrumentMandateStudioRoute
  '/_authenticated/instrument/portfolio/$ministry': typeof AuthenticatedInstrumentPortfolioMinistryRoute
  '/_authenticated/instrument/scenarios/$id': typeof AuthenticatedInstrumentScenariosIdRoute
  '/_authenticated/instrument/scenarios/compare': typeof AuthenticatedInstrumentScenariosCompareRoute
  '/_authenticated/instrument/scenarios/new': typeof AuthenticatedInstrumentScenariosNewRoute
  '/_authenticated/instrument/sector/$code': typeof AuthenticatedInstrumentSectorCodeRoute
  '/_authenticated/instrument/studio/gap': typeof AuthenticatedInstrumentStudioGapRoute
  '/_authenticated/instrument/studio/packages': typeof AuthenticatedInstrumentStudioPackagesRoute
  '/api/public/hooks/narrative-harvest': typeof ApiPublicHooksNarrativeHarvestRoute
  '/kiosk/api/public/presentation-pdf': typeof KioskApiPublicPresentationPdfRoute
  '/_authenticated/instrument/cabinet/': typeof AuthenticatedInstrumentCabinetIndexRoute
  '/_authenticated/instrument/portfolio/': typeof AuthenticatedInstrumentPortfolioIndexRoute
  '/_authenticated/instrument/scenarios/': typeof AuthenticatedInstrumentScenariosIndexRoute
  '/_authenticated/narrative/strategy/': typeof AuthenticatedNarrativeStrategyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kiosk'
    | '/instrument'
    | '/narrative'
    | '/kiosk/admin'
    | '/kiosk/'
    | '/instrument/exposure'
    | '/instrument/stewardship'
    | '/narrative/brain'
    | '/narrative/comms'
    | '/narrative/ingest'
    | '/narrative/queue'
    | '/kiosk/api/kiosk-data'
    | '/kiosk/api/upload-media'
    | '/kiosk/api/upload-presentation'
    | '/counsel/'
    | '/instrument/'
    | '/narrative/'
    | '/instrument/cabinet/session'
    | '/instrument/mandate/scorecard'
    | '/instrument/mandate/studio'
    | '/instrument/portfolio/$ministry'
    | '/instrument/scenarios/$id'
    | '/instrument/scenarios/compare'
    | '/instrument/scenarios/new'
    | '/instrument/sector/$code'
    | '/instrument/studio/gap'
    | '/instrument/studio/packages'
    | '/api/public/hooks/narrative-harvest'
    | '/kiosk/api/public/presentation-pdf'
    | '/instrument/cabinet/'
    | '/instrument/portfolio/'
    | '/instrument/scenarios/'
    | '/narrative/strategy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kiosk/admin'
    | '/kiosk'
    | '/instrument/exposure'
    | '/instrument/stewardship'
    | '/narrative/brain'
    | '/narrative/comms'
    | '/narrative/ingest'
    | '/narrative/queue'
    | '/kiosk/api/kiosk-data'
    | '/kiosk/api/upload-media'
    | '/kiosk/api/upload-presentation'
    | '/counsel'
    | '/instrument'
    | '/narrative'
    | '/instrument/cabinet/session'
    | '/instrument/mandate/scorecard'
    | '/instrument/mandate/studio'
    | '/instrument/portfolio/$ministry'
    | '/instrument/scenarios/$id'
    | '/instrument/scenarios/compare'
    | '/instrument/scenarios/new'
    | '/instrument/sector/$code'
    | '/instrument/studio/gap'
    | '/instrument/studio/packages'
    | '/api/public/hooks/narrative-harvest'
    | '/kiosk/api/public/presentation-pdf'
    | '/instrument/cabinet'
    | '/instrument/portfolio'
    | '/instrument/scenarios'
    | '/narrative/strategy'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kiosk'
    | '/_authenticated/instrument'
    | '/_authenticated/narrative'
    | '/kiosk/admin'
    | '/kiosk/'
    | '/_authenticated/instrument/exposure'
    | '/_authenticated/instrument/stewardship'
    | '/_authenticated/narrative/brain'
    | '/_authenticated/narrative/comms'
    | '/_authenticated/narrative/ingest'
    | '/_authenticated/narrative/queue'
    | '/kiosk/api/kiosk-data'
    | '/kiosk/api/upload-media'
    | '/kiosk/api/upload-presentation'
    | '/_authenticated/counsel/'
    | '/_authenticated/instrument/'
    | '/_authenticated/narrative/'
    | '/_authenticated/instrument/cabinet/session'
    | '/_authenticated/instrument/mandate/scorecard'
    | '/_authenticated/instrument/mandate/studio'
    | '/_authenticated/instrument/portfolio/$ministry'
    | '/_authenticated/instrument/scenarios/$id'
    | '/_authenticated/instrument/scenarios/compare'
    | '/_authenticated/instrument/scenarios/new'
    | '/_authenticated/instrument/sector/$code'
    | '/_authenticated/instrument/studio/gap'
    | '/_authenticated/instrument/studio/packages'
    | '/api/public/hooks/narrative-harvest'
    | '/kiosk/api/public/presentation-pdf'
    | '/_authenticated/instrument/cabinet/'
    | '/_authenticated/instrument/portfolio/'
    | '/_authenticated/instrument/scenarios/'
    | '/_authenticated/narrative/strategy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KioskRoute: typeof KioskRouteWithChildren
  ApiPublicHooksNarrativeHarvestRoute: typeof ApiPublicHooksNarrativeHarvestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/': {
      id: '/kiosk/'
      path: '/'
      fullPath: '/kiosk/'
      preLoaderRoute: typeof KioskIndexRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/admin': {
      id: '/kiosk/admin'
      path: '/admin'
      fullPath: '/kiosk/admin'
      preLoaderRoute: typeof KioskAdminRouteImport
      parentRoute: typeof KioskRoute
    }
    '/_authenticated/narrative': {
      id: '/_authenticated/narrative'
      path: '/narrative'
      fullPath: '/narrative'
      preLoaderRoute: typeof AuthenticatedNarrativeRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instrument': {
      id: '/_authenticated/instrument'
      path: '/instrument'
      fullPath: '/instrument'
      preLoaderRoute: typeof AuthenticatedInstrumentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/narrative/': {
      id: '/_authenticated/narrative/'
      path: '/'
      fullPath: '/narrative/'
      preLoaderRoute: typeof AuthenticatedNarrativeIndexRouteImport
      parentRoute: typeof AuthenticatedNarrativeRouteRoute
    }
    '/_authenticated/instrument/': {
      id: '/_authenticated/instrument/'
      path: '/'
      fullPath: '/instrument/'
      preLoaderRoute: typeof AuthenticatedInstrumentIndexRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/counsel/': {
      id: '/_authenticated/counsel/'
      path: '/counsel'
      fullPath: '/counsel/'
      preLoaderRoute: typeof AuthenticatedCounselIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/kiosk/api/upload-presentation': {
      id: '/kiosk/api/upload-presentation'
      path: '/api/upload-presentation'
      fullPath: '/kiosk/api/upload-presentation'
      preLoaderRoute: typeof KioskApiUploadPresentationRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/api/upload-media': {
      id: '/kiosk/api/upload-media'
      path: '/api/upload-media'
      fullPath: '/kiosk/api/upload-media'
      preLoaderRoute: typeof KioskApiUploadMediaRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/api/kiosk-data': {
      id: '/kiosk/api/kiosk-data'
      path: '/api/kiosk-data'
      fullPath: '/kiosk/api/kiosk-data'
      preLoaderRoute: typeof KioskApiKioskDataRouteImport
      parentRoute: typeof KioskRoute
    }
    '/_authenticated/narrative/queue': {
      id: '/_authenticated/narrative/queue'
      path: '/queue'
      fullPath: '/narrative/queue'
      preLoaderRoute: typeof AuthenticatedNarrativeQueueRouteImport
      parentRoute: typeof AuthenticatedNarrativeRouteRoute
    }
    '/_authenticated/narrative/ingest': {
      id: '/_authenticated/narrative/ingest'
      path: '/ingest'
      fullPath: '/narrative/ingest'
      preLoaderRoute: typeof AuthenticatedNarrativeIngestRouteImport
      parentRoute: typeof AuthenticatedNarrativeRouteRoute
    }
    '/_authenticated/narrative/comms': {
      id: '/_authenticated/narrative/comms'
      path: '/comms'
      fullPath: '/narrative/comms'
      preLoaderRoute: typeof AuthenticatedNarrativeCommsRouteImport
      parentRoute: typeof AuthenticatedNarrativeRouteRoute
    }
    '/_authenticated/narrative/brain': {
      id: '/_authenticated/narrative/brain'
      path: '/brain'
      fullPath: '/narrative/brain'
      preLoaderRoute: typeof AuthenticatedNarrativeBrainRouteImport
      parentRoute: typeof AuthenticatedNarrativeRouteRoute
    }
    '/_authenticated/instrument/stewardship': {
      id: '/_authenticated/instrument/stewardship'
      path: '/stewardship'
      fullPath: '/instrument/stewardship'
      preLoaderRoute: typeof AuthenticatedInstrumentStewardshipRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/exposure': {
      id: '/_authenticated/instrument/exposure'
      path: '/exposure'
      fullPath: '/instrument/exposure'
      preLoaderRoute: typeof AuthenticatedInstrumentExposureRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/narrative/strategy/': {
      id: '/_authenticated/narrative/strategy/'
      path: '/strategy'
      fullPath: '/narrative/strategy/'
      preLoaderRoute: typeof AuthenticatedNarrativeStrategyIndexRouteImport
      parentRoute: typeof AuthenticatedNarrativeRouteRoute
    }
    '/_authenticated/instrument/scenarios/': {
      id: '/_authenticated/instrument/scenarios/'
      path: '/scenarios'
      fullPath: '/instrument/scenarios/'
      preLoaderRoute: typeof AuthenticatedInstrumentScenariosIndexRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/portfolio/': {
      id: '/_authenticated/instrument/portfolio/'
      path: '/portfolio'
      fullPath: '/instrument/portfolio/'
      preLoaderRoute: typeof AuthenticatedInstrumentPortfolioIndexRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/cabinet/': {
      id: '/_authenticated/instrument/cabinet/'
      path: '/cabinet'
      fullPath: '/instrument/cabinet/'
      preLoaderRoute: typeof AuthenticatedInstrumentCabinetIndexRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/kiosk/api/public/presentation-pdf': {
      id: '/kiosk/api/public/presentation-pdf'
      path: '/api/public/presentation-pdf'
      fullPath: '/kiosk/api/public/presentation-pdf'
      preLoaderRoute: typeof KioskApiPublicPresentationPdfRouteImport
      parentRoute: typeof KioskRoute
    }
    '/api/public/hooks/narrative-harvest': {
      id: '/api/public/hooks/narrative-harvest'
      path: '/api/public/hooks/narrative-harvest'
      fullPath: '/api/public/hooks/narrative-harvest'
      preLoaderRoute: typeof ApiPublicHooksNarrativeHarvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/instrument/studio/packages': {
      id: '/_authenticated/instrument/studio/packages'
      path: '/studio/packages'
      fullPath: '/instrument/studio/packages'
      preLoaderRoute: typeof AuthenticatedInstrumentStudioPackagesRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/studio/gap': {
      id: '/_authenticated/instrument/studio/gap'
      path: '/studio/gap'
      fullPath: '/instrument/studio/gap'
      preLoaderRoute: typeof AuthenticatedInstrumentStudioGapRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/sector/$code': {
      id: '/_authenticated/instrument/sector/$code'
      path: '/sector/$code'
      fullPath: '/instrument/sector/$code'
      preLoaderRoute: typeof AuthenticatedInstrumentSectorCodeRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/scenarios/new': {
      id: '/_authenticated/instrument/scenarios/new'
      path: '/scenarios/new'
      fullPath: '/instrument/scenarios/new'
      preLoaderRoute: typeof AuthenticatedInstrumentScenariosNewRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/scenarios/compare': {
      id: '/_authenticated/instrument/scenarios/compare'
      path: '/scenarios/compare'
      fullPath: '/instrument/scenarios/compare'
      preLoaderRoute: typeof AuthenticatedInstrumentScenariosCompareRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/scenarios/$id': {
      id: '/_authenticated/instrument/scenarios/$id'
      path: '/scenarios/$id'
      fullPath: '/instrument/scenarios/$id'
      preLoaderRoute: typeof AuthenticatedInstrumentScenariosIdRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/portfolio/$ministry': {
      id: '/_authenticated/instrument/portfolio/$ministry'
      path: '/portfolio/$ministry'
      fullPath: '/instrument/portfolio/$ministry'
      preLoaderRoute: typeof AuthenticatedInstrumentPortfolioMinistryRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/mandate/studio': {
      id: '/_authenticated/instrument/mandate/studio'
      path: '/mandate/studio'
      fullPath: '/instrument/mandate/studio'
      preLoaderRoute: typeof AuthenticatedInstrumentMandateStudioRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/mandate/scorecard': {
      id: '/_authenticated/instrument/mandate/scorecard'
      path: '/mandate/scorecard'
      fullPath: '/instrument/mandate/scorecard'
      preLoaderRoute: typeof AuthenticatedInstrumentMandateScorecardRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
    '/_authenticated/instrument/cabinet/session': {
      id: '/_authenticated/instrument/cabinet/session'
      path: '/cabinet/session'
      fullPath: '/instrument/cabinet/session'
      preLoaderRoute: typeof AuthenticatedInstrumentCabinetSessionRouteImport
      parentRoute: typeof AuthenticatedInstrumentRouteRoute
    }
  }
}

interface AuthenticatedInstrumentRouteRouteChildren {
  AuthenticatedInstrumentExposureRoute: typeof AuthenticatedInstrumentExposureRoute
  AuthenticatedInstrumentStewardshipRoute: typeof AuthenticatedInstrumentStewardshipRoute
  AuthenticatedInstrumentIndexRoute: typeof AuthenticatedInstrumentIndexRoute
  AuthenticatedInstrumentCabinetSessionRoute: typeof AuthenticatedInstrumentCabinetSessionRoute
  AuthenticatedInstrumentMandateScorecardRoute: typeof AuthenticatedInstrumentMandateScorecardRoute
  AuthenticatedInstrumentMandateStudioRoute: typeof AuthenticatedInstrumentMandateStudioRoute
  AuthenticatedInstrumentPortfolioMinistryRoute: typeof AuthenticatedInstrumentPortfolioMinistryRoute
  AuthenticatedInstrumentScenariosIdRoute: typeof AuthenticatedInstrumentScenariosIdRoute
  AuthenticatedInstrumentScenariosCompareRoute: typeof AuthenticatedInstrumentScenariosCompareRoute
  AuthenticatedInstrumentScenariosNewRoute: typeof AuthenticatedInstrumentScenariosNewRoute
  AuthenticatedInstrumentSectorCodeRoute: typeof AuthenticatedInstrumentSectorCodeRoute
  AuthenticatedInstrumentStudioGapRoute: typeof AuthenticatedInstrumentStudioGapRoute
  AuthenticatedInstrumentStudioPackagesRoute: typeof AuthenticatedInstrumentStudioPackagesRoute
  AuthenticatedInstrumentCabinetIndexRoute: typeof AuthenticatedInstrumentCabinetIndexRoute
  AuthenticatedInstrumentPortfolioIndexRoute: typeof AuthenticatedInstrumentPortfolioIndexRoute
  AuthenticatedInstrumentScenariosIndexRoute: typeof AuthenticatedInstrumentScenariosIndexRoute
}

const AuthenticatedInstrumentRouteRouteChildren: AuthenticatedInstrumentRouteRouteChildren =
  {
    AuthenticatedInstrumentExposureRoute: AuthenticatedInstrumentExposureRoute,
    AuthenticatedInstrumentStewardshipRoute:
      AuthenticatedInstrumentStewardshipRoute,
    AuthenticatedInstrumentIndexRoute: AuthenticatedInstrumentIndexRoute,
    AuthenticatedInstrumentCabinetSessionRoute:
      AuthenticatedInstrumentCabinetSessionRoute,
    AuthenticatedInstrumentMandateScorecardRoute:
      AuthenticatedInstrumentMandateScorecardRoute,
    AuthenticatedInstrumentMandateStudioRoute:
      AuthenticatedInstrumentMandateStudioRoute,
    AuthenticatedInstrumentPortfolioMinistryRoute:
      AuthenticatedInstrumentPortfolioMinistryRoute,
    AuthenticatedInstrumentScenariosIdRoute:
      AuthenticatedInstrumentScenariosIdRoute,
    AuthenticatedInstrumentScenariosCompareRoute:
      AuthenticatedInstrumentScenariosCompareRoute,
    AuthenticatedInstrumentScenariosNewRoute:
      AuthenticatedInstrumentScenariosNewRoute,
    AuthenticatedInstrumentSectorCodeRoute:
      AuthenticatedInstrumentSectorCodeRoute,
    AuthenticatedInstrumentStudioGapRoute:
      AuthenticatedInstrumentStudioGapRoute,
    AuthenticatedInstrumentStudioPackagesRoute:
      AuthenticatedInstrumentStudioPackagesRoute,
    AuthenticatedInstrumentCabinetIndexRoute:
      AuthenticatedInstrumentCabinetIndexRoute,
    AuthenticatedInstrumentPortfolioIndexRoute:
      AuthenticatedInstrumentPortfolioIndexRoute,
    AuthenticatedInstrumentScenariosIndexRoute:
      AuthenticatedInstrumentScenariosIndexRoute,
  }

const AuthenticatedInstrumentRouteRouteWithChildren =
  AuthenticatedInstrumentRouteRoute._addFileChildren(
    AuthenticatedInstrumentRouteRouteChildren,
  )

interface AuthenticatedNarrativeRouteRouteChildren {
  AuthenticatedNarrativeBrainRoute: typeof AuthenticatedNarrativeBrainRoute
  AuthenticatedNarrativeCommsRoute: typeof AuthenticatedNarrativeCommsRoute
  AuthenticatedNarrativeIngestRoute: typeof AuthenticatedNarrativeIngestRoute
  AuthenticatedNarrativeQueueRoute: typeof AuthenticatedNarrativeQueueRoute
  AuthenticatedNarrativeIndexRoute: typeof AuthenticatedNarrativeIndexRoute
  AuthenticatedNarrativeStrategyIndexRoute: typeof AuthenticatedNarrativeStrategyIndexRoute
}

const AuthenticatedNarrativeRouteRouteChildren: AuthenticatedNarrativeRouteRouteChildren =
  {
    AuthenticatedNarrativeBrainRoute: AuthenticatedNarrativeBrainRoute,
    AuthenticatedNarrativeCommsRoute: AuthenticatedNarrativeCommsRoute,
    AuthenticatedNarrativeIngestRoute: AuthenticatedNarrativeIngestRoute,
    AuthenticatedNarrativeQueueRoute: AuthenticatedNarrativeQueueRoute,
    AuthenticatedNarrativeIndexRoute: AuthenticatedNarrativeIndexRoute,
    AuthenticatedNarrativeStrategyIndexRoute:
      AuthenticatedNarrativeStrategyIndexRoute,
  }

const AuthenticatedNarrativeRouteRouteWithChildren =
  AuthenticatedNarrativeRouteRoute._addFileChildren(
    AuthenticatedNarrativeRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInstrumentRouteRoute: typeof AuthenticatedInstrumentRouteRouteWithChildren
  AuthenticatedNarrativeRouteRoute: typeof AuthenticatedNarrativeRouteRouteWithChildren
  AuthenticatedCounselIndexRoute: typeof AuthenticatedCounselIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInstrumentRouteRoute:
    AuthenticatedInstrumentRouteRouteWithChildren,
  AuthenticatedNarrativeRouteRoute:
    AuthenticatedNarrativeRouteRouteWithChildren,
  AuthenticatedCounselIndexRoute: AuthenticatedCounselIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface KioskRouteChildren {
  KioskAdminRoute: typeof KioskAdminRoute
  KioskIndexRoute: typeof KioskIndexRoute
  KioskApiKioskDataRoute: typeof KioskApiKioskDataRoute
  KioskApiUploadMediaRoute: typeof KioskApiUploadMediaRoute
  KioskApiUploadPresentationRoute: typeof KioskApiUploadPresentationRoute
  KioskApiPublicPresentationPdfRoute: typeof KioskApiPublicPresentationPdfRoute
}

const KioskRouteChildren: KioskRouteChildren = {
  KioskAdminRoute: KioskAdminRoute,
  KioskIndexRoute: KioskIndexRoute,
  KioskApiKioskDataRoute: KioskApiKioskDataRoute,
  KioskApiUploadMediaRoute: KioskApiUploadMediaRoute,
  KioskApiUploadPresentationRoute: KioskApiUploadPresentationRoute,
  KioskApiPublicPresentationPdfRoute: KioskApiPublicPresentationPdfRoute,
}

const KioskRouteWithChildren = KioskRoute._addFileChildren(KioskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KioskRoute: KioskRouteWithChildren,
  ApiPublicHooksNarrativeHarvestRoute: ApiPublicHooksNarrativeHarvestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
